### ISSUE TITLE
reproduce problem of gpt-3.5-turbo on turn-based short:

### ISSUE THREAD

**Issue by jiashenggu** [gydpku/PPTC#4]
I try to reproduce the results of gpt-3.5-turbo.
But I got the following results on turn-based short:

> avg api cost: 3.1204379562043796
> avg_token_costs: 1328.153892944039
> string acc: 780/1644=0.4744525547445255
> position acc: 28/282=0.09929078014184398

I have made the following changes to the openai api input as per the requirements of the api:

```
# prompt = "<|im_start|>system\nYou are a helpful assistant.\n<|im_end|>\n<|im_start|>user\nHello!\n<|im_end|>\n<|im_start|>assistant\nHow can I help you?\n<|im_end|>\n<|im_start|>user\n{0}\n<|im_end|>\n<|im_start|>assistant\n".format(query)
messages = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Hello!"},
    {"role": "assistant", "content": "How can I help you?"},
    {"role": "user", "content": query},
]
response = chat_with_backoff(
    # model="gpt-35-turbo",
    model="gpt-3.5-turbo",
    # prompt=prompt,
    messages=messages,
    temperature=0,
    max_tokens=1000,
    top_p=0.95,
    frequency_penalty=0,
    presence_penalty=0,
    stop=["<|im_end|>", "¬User¬", "</decomposed>","</query>"])
```
Can you think of any reasons for a significant drop in performance?

**Comment by gydpku** [comment]
Hi, our ChatGPT turbo version is 0315 and its API is provided by Azure. Maybe the deployed chatgpt models from different provider are not the same.

**Comment by jiashenggu** [comment]
@gydpku Hi, I noticed that certain parameters are not used in the README.md example. Is it possible that the performance degradation is coming from certain parameter settings?
```
    parser.add_argument("--planning", default=False, action='store_true',
                        help="whether to apply the planning module") 
    parser.add_argument("--api_selection", default=False, action='store_true',
                        help="whether to apply the api selection module") 
    parser.add_argument("--api_topk", default=10, type=int,
                        help="How many apis to retrieve from the api pool") 
    parser.add_argument("--content_selection", default=False, action='store_true',
                        help="whether to apply the shape selection module") 
```

**Comment by gydpku** [comment]
No, these parameters are used in the planning and selection algorithms. Their results are in Table 2. No using them would not influence the LLM's performance.
