### ISSUE TITLE
Where to obtain my "api_base"?

### ISSUE THREAD

**Issue by HelloWorld4747** [gydpku/PPTC#6]
Hello,

First thing first, thank you so much for sharing such impressive idea with us!

I was trying to regenerate the results mentioned in your paper. Unluckily, I was stuck in the first step, which ask me to fill in "api_base" (please refer to the image below). I created my account directly from the openai website. I only have openai_api_key. May I please ask you where to obtain the "api_base"? I am still pretty new in this area. Please do correct me if any of my understanding is incorrect.
![image](https://github.com/gydpku/PPTC/assets/100496010/7c38a1eb-f561-4e90-ac8f-2f2347cfc9a3)

Appreciate all the response!

**Comment by gydpku** [comment]
Well,  If you creat your account directly from the openai website, you do not need an api_base.  Just follow the steps in openai and make sure the output in line 105.
