### ISSUE TITLE
How to do next when getting embedding for create a slide

### ISSUE THREAD

**Issue by Benedict-Y** [gydpku/PPTC#8]
Hello,
I tried to reproduce this impressive project in Google Colab. I tried to use GPT 3.5 to generate PPT file. When I executed "python3 PPTC/main.py --prepare --dataset long" command, the program stopped and showed that "getting embedding for create a slide". More details are shown in the following figure and pdf file.

![image](https://github.com/gydpku/PPTC/assets/104419622/1e6447a1-47fd-4d44-894f-ddb9391bca87)

[PPTC.ipynb - Colaboratory.pdf](https://github.com/gydpku/PPTC/files/14626915/PPTC.ipynb.-.Colaboratory.pdf)
Could you please tell me how to continue, thanks.

**Comment by gydpku** [comment]
Hi,
do you put the file [api_embeddings.pkl](https://github.com/gydpku/PPTC/blob/main/api_embeddings.pkl) into your folder? It contains the embeddings needed for experiments.

**Comment by Benedict-Y** [comment]
Thanks for your reply! I have put the file api_embeddings.pkl into the folder. But the program just stop at that command.I wonder if multiple commands need to be run at the same time. Thanks!
