### ISSUE TITLE
Questions about experimental details

### ISSUE THREAD

**Issue by XinrunXu** [gydpku/PPTC#9]
In the experiments in Table 1, did you use the Content Selection algorithm and API Selection algorithm?
In Table 2:
If you do not use the Content Selection algorithm, do you directly input all the content output by the Python-PPTX Content Reader Module into the model?
If you don't use the API Selection algorithm, do you input a random API file in the prompt?

**Comment by gydpku** [comment]
Hi Xu, we do not use the Content Selection algorithm and API Selection algorithm in Table 1.
Yes, we directly input all the content output by the Python-PPTX Content Reader Module and input the API file in the prompt.
The API file contains all feasible APIs and is fixed.
